### ISSUE TITLE
Non-ASCII character '\xf0'

### ISSUE THREAD

**Issue by matarrese** [defaultnamehere/tinder-detective#11]
python app.py
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    import api
  File "/Users/antoniomatarrese/tinder-detective/api.py", line 69
SyntaxError: Non-ASCII character '\xf0' in file /Users/antoniomatarrese/tinder-detective/api.py on line 69, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by krijoh92** [comment]
You can insert `# -*- coding: utf-8 -*-` on top of api.py and app.py and that would fix the problem :)

**Comment by matarrese** [comment]
@krijoh92 your solution is working
