### ISSUE TITLE
builtins.UnicodeEncodeError

### ISSUE THREAD

**Issue by WurstCommander** [defaultnamehere/tinder-detective#12]
After starting the app and going to localhost:5000

I get the following error:

builtins.UnicodeEncodeError

UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f512' in position 91: character maps to <undefined>

Traceback (most recent call last)
File "C:\python30\lib\site-packages\flask\app.py", line 2000, in **call**
return self.wsgi_app(environ, start_response)
File "C:\python30\lib\site-packages\flask\app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\python30\lib\site-packages\flask\app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\python30\lib\site-packages\flask_compat.py", line 33, in reraise
raise value
File "C:\python30\lib\site-packages\flask\app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "C:\python30\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\python30\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\python30\lib\site-packages\flask_compat.py", line 33, in reraise
raise value
File "C:\python30\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "C:\python30\lib\site-packages\flask\app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "D:\0815_Spielwiese\tinder-detective-master\app.py", line 13, in index
profiles = stalker.get_profiles()
File "D:\0815_Spielwiese\tinder-detective-master\api.py", line 142, in get_profiles
friends = self.get_facebook_friends_tinder_ids()
File "D:\0815_Spielwiese\tinder-detective-master\api.py", line 85, in get_facebook_friends_tinder_ids
be_creepy = input("Sure you want to look at your Facebook friends' Tinder profiles? They might not like that. 🔒 [y/n]: ").lower() in ("y", "yes")
File "C:\python30\lib\encodings\cp850.py", line 12, in encode
return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f512' in position 91: character maps to <undefined>

**Comment by Mardelove** [comment]
It's because the cmd can't read the file, i found this bat file that helped me fix the issue.
(Choose 1)

/////////////////////

@ECHO off

SET ROOT_KEY="HKEY_CURRENT_USER"


FOR /f "skip=2 tokens=3" %%i in ('reg query HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage /v OEMCP') do set OEMCP=%%i

ECHO System default values:

ECHO.
ECHO ...............................................
ECHO Select Codepage 
ECHO ...............................................
ECHO.
ECHO 1 - CP1252
ECHO 2 - UTF-8
ECHO 3 - CP850
ECHO 4 - ISO-8859-1
ECHO 5 - ISO-8859-15
ECHO 6 - US-ASCII
ECHO.
ECHO 9 - Reset to System Default (CP%OEMCP%)
ECHO 0 - EXIT
ECHO.


SET /P  CP="Select a Codepage: "

if %CP%==1 (
    echo Set default Codepage to CP1252
    reg add "%ROOT_KEY%\Software\Microsoft\Command Processor" /v Autorun /t REG_SZ /d "chcp 1252" /f
) else if %CP%==2 (
    echo Set default Codepage to UTF-8
    reg add "%ROOT_KEY%\Software\Microsoft\Command Processor" /v Autorun /t REG_SZ /d "chcp 65001" /f
) else if %CP%==3 (
    echo Set default Codepage to CP850
    reg add "%ROOT_KEY%\Software\Microsoft\Command Processor" /v Autorun /t REG_SZ /d "chcp 850" /f
) else if %CP%==4 (
    echo Set default Codepage to ISO-8859-1
    add "%ROOT_KEY%\Software\Microsoft\Command Processor" /v Autorun /t REG_SZ /d "chcp 28591" /f
) else if %CP%==5 (
    echo Set default Codepage to ISO-8859-15
    add "%ROOT_KEY%\Software\Microsoft\Command Processor" /v Autorun /t REG_SZ /d "chcp 28605" /f
) else if %CP%==5 (
    echo Set default Codepage to ASCII
    add "%ROOT_KEY%\Software\Microsoft\Command Processor" /v Autorun /t REG_SZ /d "chcp 20127" /f
) else if %CP%==9 (
    echo Reset Codepage to System Default
    reg delete "%ROOT_KEY%\Software\Microsoft\Command Processor" /v AutoRun /f
) else if %CP%==0 (
    echo Bye
) else (
    echo Invalid choice
    pause
)

**Comment by esquire900** [comment]
In windows cli, run "chcp 65001"

**Comment by highnold** [comment]
Same problem, cant seem to get it fixed

**Comment by hrosdei** [comment]
I have the same issue. Were you able to resolve the problem @WurstCommander?

**Comment by WurstCommander** [comment]
chcp 65001 before executing the app solved it.

but I opend the *.py files in pycharm and saved, maybe it changed the encoding too?

**Comment by ghost** [comment]
advice from an utter n00b:
Issue from what I can tell are the emojis used throughout api.py - I just replaced those with plaintext and it started playing nicely again.
