### ISSUE TITLE
Python Datetime Timezone Issue

### ISSUE THREAD

**Issue by sibblegp** [defaultnamehere/tinder-detective#13]
python app.py  
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    import api
  File "/apps/tinder-detective/api.py", line 7, in <module>
    from datetime import timezone
ImportError: cannot import name timezone

I don't think Python 2.7 has timezone but 3.X won't run Flask.  What am I missing here?

**Comment by sibblegp** [comment]
When I try to run under 3.X:

Traceback (most recent call last):
  File "app.py", line 7, in <module>
    app = Flask('tinder-detective')
  File "/apps/tinder-detective/env_tinder_detective/lib/python3.4/site-packages/flask/app.py", line 346, in **init**
    root_path=root_path)
  File "/apps/tinder-detective/env_tinder_detective/lib/python3.4/site-packages/flask/helpers.py", line 807, in **init**
    root_path = get_root_path(self.import_name)
  File "/apps/tinder-detective/env_tinder_detective/lib/python3.4/site-packages/flask/helpers.py", line 657, in get_root_path
    loader = pkgutil.get_loader(import_name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pkgutil.py", line 469, in get_loader
    return find_loader(fullname)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pkgutil.py", line 490, in find_loader
    return spec.loader
AttributeError: 'NoneType' object has no attribute 'loader'

**Comment by matarrese** [comment]
Having some error: Mac OSX

**Comment by raed667** [comment]
Same error Windows 8.1

**Comment by Beertie** [comment]
Set 
from datetime import timezone
TO
from datetime import datetime

**Comment by rafael-azevedo** [comment]
on OSX run pip3 install datetime

**Comment by gregorylivschitz** [comment]
Concerning the NoneType loader issue. This is happening because you are running python3.40, there seems to be a bug with that version and flask. I ran into this problem.

If you change the python version to 3.43+ it should work.
Here is the github thread for reference:
https://github.com/pallets/flask/issues/1011

**Comment by sibblegp** [comment]
> Set
> from datetime import timezone
> TO
> from datetime import datetime

This worked.  Thanks!
