### ISSUE TITLE
Traceback Error:  stalker = api.NSASimulator()

### ISSUE THREAD

**Issue by staticabhi** [defaultnamehere/tinder-detective#22]
Hey, got the following error:
using the Facebook id i fetched from my facebook app

_Traceback (most recent call last):
  File "app.py", line 9, in <module>
    stalker = api.NSASimulator()
  File "C:\Users\ArorAb01\Desktop\tinder-detective-master\tinder-detective-master\api.py", line 42, in __init__
    self._load_fb_auth()
  File "C:\Users\ArorAb01\Desktop\tinder-detective-master\tinder-detective-master\api.py", line 51, in _load_fb_auth
    self.fb_auth = json.load(f)
  File "C:\Anaconda3\lib\json__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Anaconda3\lib\json__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)_

**Comment by AlexBailey** [comment]
Why close with no solution, how did you solve this?
