### ISSUE TITLE
What to do when you get into localhost:5000 ?

### ISSUE THREAD

**Issue by staticabhi** [defaultnamehere/tinder-detective#23]
What to do when you get into localhost:5000 in your browser how to write "Y"?

**Comment by yanirz** [comment]
You press "Y" in the console where you ran the server.

**Comment by staticabhi** [comment]
I did.. but then got the following error:

_builtins.UnicodeEncodeError
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f608' in position 0: character maps to <undefined>

Traceback (most recent call last)
File "C:\Anaconda3\lib\site-packages\flask\app.py", line 2000, in **call**
return self.wsgi_app(environ, start_response)
File "C:\Anaconda3\lib\site-packages\flask\app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\Anaconda3\lib\site-packages\flask\app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Anaconda3\lib\site-packages\flask_compat.py", line 33, in reraise
raise value
File "C:\Anaconda3\lib\site-packages\flask\app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "C:\Anaconda3\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Anaconda3\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Anaconda3\lib\site-packages\flask_compat.py", line 33, in reraise_

**Comment by yanirz** [comment]
I see you're running from Windows, I'd generally suggest running from a Linux machine so you'll have a unicode support. You could remove all Unicode emojis from the code or try checking the solution on #11 and see if it helps you.
