### ISSUE TITLE
Multiple error mesages

### ISSUE THREAD

**Issue by mathisen99** [defaultnamehere/tinder-detective#24]
Hello i am getting multiple error mesages...
am i missing something here ??
# python3 app.py

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    stalker = api.NSASimulator()
  File "/home/mathisen/tinder/tinder-detective/api.py", line 42, in **init**
    self._load_fb_auth()
  File "/home/mathisen/tinder/tinder-detective/api.py", line 51, in _load_fb_auth
    self.fb_auth = json.load(f)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/**init**.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by tibeoh** [comment]
Hi,
I had the same error, you have a synthax error in your `SECRETS.json` file.

```
{
        "facebook_id": "XXX",
        "facebook_token": "XXXX"
}
```

Check if you don't forget a quote.

**Comment by mathisen99** [comment]
ahh yes that did the trick! thx.. 
one more thing i cant seem to reach the remote server im running it on..
is it only localhost that can reach it ?

port is open and not used

**Comment by yanirz** [comment]
@mathisen99 in app.py change to this:
`app.run(debug=True, host="0.0.0.0")`

**Comment by mathisen99** [comment]
worked like a charm! thx both of you :)
