### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f512' in position 91: character maps to <undefined>

### ISSUE THREAD

**Issue by RobertPaulson90** [defaultnamehere/tinder-detective#34]
Traceback (most recent call last)
File "C:\python35\lib\site-packages\flask\app.py", line 2000, in **call**
return self.wsgi_app(environ, start_response)
File "C:\python35\lib\site-packages\flask\app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\python35\lib\site-packages\flask\app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\python35\lib\site-packages\flask_compat.py", line 33, in reraise
raise value
File "C:\python35\lib\site-packages\flask\app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "C:\python35\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\python35\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\python35\lib\site-packages\flask_compat.py", line 33, in reraise
raise value
File "C:\python35\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "C:\python35\lib\site-packages\flask\app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Users\Trump\Downloads\New folder (9)\tinder-detective-master\app.py", line 13, in index
profiles = stalker.get_profiles()
File "C:\Users\Trump\Downloads\New folder (9)\tinder-detective-master\api.py", line 142, in get_profiles
friends = self.get_facebook_friends_tinder_ids()
File "C:\Users\Trump\Downloads\New folder (9)\tinder-detective-master\api.py", line 85, in get_facebook_friends_tinder_ids
be_creepy = input("Sure you want to look at your Facebook friends' Tinder profiles? They might not like that. 🔒 [y/n]: ").lower() in ("y", "yes")
File "C:\python35\lib\encodings\cp437.py", line 12, in encode
return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f512' in position 91: character maps to <undefined>

**Comment by uint16** [comment]
There's a workaround for this, look at comments on issue #12

**Comment by RobertPaulson90** [comment]
Thanks I found a different stackoverflow thread with the same command, and it worked. Or at least got me further. In the console it now says:
- Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
- Restarting with stat
- Debugger is active!
- Debugger pin code: 221-750-094
  Authenticated to Tinder ðŸ”’ðŸ”¥
  {"status":200,"results":[]}
  127.0.0.1 - - [25/Jul/2016 20:19:45] "GET / HTTP/1.1" 200 -

Looks like there's still an issue with the encoding (im on Windows). On the site all I see is the following message, no content below:

Tinder detective I guess
"It's important to note Tinder's not a secret considering 70% of users download Tinder because their friends recommend

**Comment by RobertPaulson90** [comment]
Ah checking the code I'm most likely a moron :) 

class SquadError(Exception):
    """I have no excuse for this one."""
if request.status_code != 200:
            raise SquadError("Couldn't get info about your friends. Is Tinder Social enabled on your account? Hint: If you're not in Australia it probably isn't.")

I just have no idea how to enable "Tinder Social"

**Comment by wjdavis5** [comment]
You open the tinder app and enable social for the account.

**Comment by freemandyson** [comment]
I'm having the same UnicodeEncodeError, and the chcp 65001 workaround doesn't seem to fix it. Any other ideas?
