### ISSUE TITLE
ImportError: No module named 'dateutil'

### ISSUE THREAD

**Issue by CryptoCrook** [defaultnamehere/tinder-detective#39]
After installing the wheel package and the flask and requests modules, I am still getting an error saying:

```

C:\Users\admin\Desktop\tinder-detective-master>python app.py
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    import api
  File "C:\Users\admin\Desktop\tinder-detective-master\api.py", line 5, in <module>
    from dateutil import parser
ImportError: No module named 'dateutil'
```

I attempted to install it with `pip install dateutil`and got back 

```
Collecting dateutil
  Could not find a version that satisfies the requirement dateutil (from versions: )
No matching distribution found for dateutil

```

I am Running Windows 10 x64 with Python 3.5.2 32bit installed.

**Comment by CryptoCrook** [comment]
Fixed with `pip install python-dateutil`
