### ISSUE TITLE
Requirement already satisfied

### ISSUE THREAD

**Issue by mdutton27** [defaultnamehere/tinder-detective#41]
When I try to run requirements.text I get the following:

pip3 install -r /Users/michaelddutton/Downloads/tinder-detective-master/requirements.txt
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/michaelddutton/Downloads/tinder-detective-master/requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/michaelddutton/Downloads/tinder-detective-master/requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/michaelddutton/Downloads/tinder-detective-master/requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/michaelddutton/Downloads/tinder-detective-master/requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/michaelddutton/Downloads/tinder-detective-master/requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil==2.5.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/michaelddutton/Downloads/tinder-detective-master/requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/michaelddutton/Downloads/tinder-detective-master/requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/michaelddutton/Downloads/tinder-detective-master/requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r /Users/michaelddutton/Downloads/tinder-detective-master/requirements.txt (line 9))

When I upgrade those items, I get: Requirement already up-to-date:

What am I doing wrong?

**Comment by uint16** [comment]
That means all the modules are already installed and you are good to run the app... Just make sure you run it with python3.

**Comment by mdutton27** [comment]
Thanks @damagination, perhaps you could do one last favour and tell me why I'm getting this:

OH-michaeld-MBP:~ michaeld$ python3 /Users/michaeld/Dropbox/tinder-detective-master/app.py
Traceback (most recent call last):
  File "/Users/michaeld/Dropbox/tinder-detective-master/app.py", line 9, in <module>
    stalker = api.NSASimulator()
  File "/Users/michaeld/Dropbox/tinder-detective-master/api.py", line 42, in **init**
    self._load_fb_auth()
  File "/Users/michaeld/Dropbox/tinder-detective-master/api.py", line 53, in _load_fb_auth
    raise AuthenticationError("Couldn't find {secrets_filename}. Did you create it and put your Facebook user id and auth token in it?".format(secrets_filename=SECRETS_FILENAME))
api.AuthenticationError: Couldn't find SECRETS.json. Did you create it and put your Facebook user id and auth token in it?

I've updated my SECRETS.json with a new auth token since my previous one expired.  Any idea why it's failing now?   I've made sure there's no extra lines or spaces in the secrets.
