### ISSUE TITLE
cannot import flask from flask even after creating virtual env and installing flask          pip install -U Flask Requirement already up-to-date: Flask in ./flask-env/lib/python3.8/site-packages (1.1.2) Requirement already satisfied, skipping upgrade: Jinja2>=2.10.1 in ./flask-env/lib/python3.8/site-packages (from Flask) (2.11.2) Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in ./flask-env/lib/python3.8/site-packages (from Flask) (1.1.0) Requirement already satisfied, skipping upgrade: Werkzeug>=0.15 in ./flask-env/lib/python3.8/site-packages (from Flask) (1.0.1) Requirement already satisfied, skipping upgrade: click>=5.1 in ./flask-env/lib/python3.8/site-packages (from Flask) (7.1.1) Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in ./flask-env/lib/python3.8/site-packages (from Jinja2>=2.10.1->Flask) (1.1.1)

### ISSUE THREAD

**Issue by RexAgarwal** [defaultnamehere/tinder-detective#56]
127.0.0.1 - - [25/Apr/2020 22:31:25] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/mnt/c/project0/project0/flask-application/ap.py", line 1, in <module>
    from flask import flask
ImportError: cannot import name 'flask' from 'flask' (/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/flask/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/flask/cli.py", line 338, in __call__
    self._flush_bg_loading_exception()
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/flask/cli.py", line 326, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/flask/cli.py", line 314, in _load_app
    self._load_unlocked()
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/flask/cli.py", line 245, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing "ap", an ImportError was raised:

Traceback (most recent call last):
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/mnt/c/project0/project0/flask-application/ap.py", line 1, in <module>
    from flask import flask
ImportError: cannot import name 'flask' from 'flask' (/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/flask/__init__.py)
127.0.0.1 - - [25/Apr/2020 22:31:26] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2020 22:31:26] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2020 22:31:26] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2020 22:31:26] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2020 22:31:26] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2020 22:31:26] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2020 22:32:39] "GET /?__debugger__=yes&tb=139682065603456&cmd=paste&s=0eihAxbruzRccWmumclD HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/werkzeug/debug/__init__.py", line 479, in __call__
    response = self.paste_traceback(request, traceback)
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/werkzeug/debug/__init__.py", line 370, in paste_traceback
    rv = traceback.paste()
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/werkzeug/debug/tbtools.py", line 299, in paste
    rv = urlopen("https://api.github.com/gists", data=data)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
127.0.0.1 - - [25/Apr/2020 22:32:46] "GET /?__debugger__=yes&tb=139682065603456&cmd=paste&s=0eihAxbruzRccWmumclD HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/werkzeug/debug/__init__.py", line 479, in __call__
    response = self.paste_traceback(request, traceback)
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/werkzeug/debug/__init__.py", line 370, in paste_traceback
    rv = traceback.paste()
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/werkzeug/debug/tbtools.py", line 299, in paste
    rv = urlopen("https://api.github.com/gists", data=data)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by RexAgarwal** [comment]
flask.cli.NoAppException: While importing "ap", an ImportError was raised:

Traceback (most recent call last):
  File "/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/mnt/c/project0/project0/flask-application/flask-env/ap.py", line 1, in <module>
    from flask import flask
ImportError: cannot import name 'flask' from 'flask' (/mnt/c/project0/project0/flask-application/flask-env/lib/python3.8/site-packages/flask/__init__.py)
